---
title: "TRABAJO Nº3 - GRUPO 4"
output:
  html_document: default
  pdf_document: default
date: "2023-11-22"
---

\*\*Desarrollo de la práctica\*\* \

------------------------------------------------------------------------

#  Se instala e importa las siguientes librerias

install.packages("lubridate") install.packages("tidyverse") install.packages("stringr") install.packages("dplyr") install.packages("vetiver") install.packages("lubridate")

if (!requireNamespace("writexl", quietly = TRUE)) { install.packages("writexl") }

#Leer el archivo epa http.cvs library(readr) library(dplyr) library(stringr) library(lubridate) library(writexl)

#Librerias kmeans library(mltools) library(data.table)

# OBTENCIÓN Y CARGA DE LOS DATOS

## Se requiere programar un script con el que podamos hacer una investigación forense sobre un fichero de logs de un servidor de tipo Apache. Los datos del registro del servidor están en el formato estándar e incluyen miles de registros sobre las distintas peticiones gestionadas por el servidor web.

####################### PREGUNTA 1 - INICIO\

epa_http \<- read_table("epa-http.csv", col_names = FALSE)

# Cambiar el nombre de las columnas:

colnames(epa_http)[1]\<-"origen" colnames(epa_http)[2]\<-"dataTimeStamp" colnames(epa_http)[3]\<-"metodoHttp" colnames(epa_http)[4]\<-"uri" colnames(epa_http)[5]\<-"protocolo" colnames(epa_http)[6]\<-"respuestaHttp" colnames(epa_http)[7]\<-"bytes"

# Normalizar la información de columnas:

epa_http$metodoHttp <- gsub('^"|"$','', epa_http$metodoHttp) epa_http$protocolo \<- gsub('\^"\|"$', '', epa_http$protocolo) epa_http$dataTimeStamp <- as.POSIXct(epa_http$dataTimeStamp,format="[%d:%H:%M:%S]",tz = "utc")\
epa_http$bytes <- as.numeric(epa_http$bytes) epa_http$bytes <- epa_http$bytes \<- ifelse(is.na(epa_http$bytes), 0, epa_http$bytes) epa_http$origen <- str_trim(epa_http$origen) View(epa_http)

# Validar si la columna es de tipo "Date"

if (all(is.Date(epa_http$dataTimeStamp))) { print("La columna dataTimeStamp es de tipo Date.") } else { print("La columna dataTimeStamp no es de tipo Date.") print(class(epa_http$dataTimeStamp)) }

####################### PREGUNTA 1 - FIN\

# EXPLORACIÓN DE DATOS

## Identificar el número único de usuarios que han interactuado directamente con el servidor de forma segregada según si los usuarios han tenido algún tipo de error en las distintas peticiones ofrecidas por el servidor.

####################### PREGUNTA 2 - INICIO\

## NORMALIZANDO la información de HREF, convirtiendo una URL "Relativa" a "Absoluta" (tipo2)

epa_http \<- epa_http %\>% mutate( exitoso = case_when( stringr::str_detect(respuestaHttp, "[^1]") \~ TRUE, TRUE \~ FALSE ) )

[^1]: 123

p1_df \<- epa_http %\>% group_by(origen,exitoso) %\>% summarise(peticiones = n()) View(p1_df)

####################### PREGUNTA 2 - FIN\

# ANÁLISIS DE DATOS

## Analizar los distintos tipos de peticiones HTTP (GET, POST, PUT, DELETE) gestionadas por el servidor, identificando la frecuencia de cada una de estas. Repetir el análisis, esta vez filtrando previamente aquellas peticiones correspondientes a recursos ofrecidos de tipo imagen.

####################### PREGUNTA 3 - INICIO\

# Filtrar y agregar a una columna nueva si es archivo de imagen

epa_http \<- epa_http %\>% mutate( is_image = case_when( stringr::str_detect(uri, "(?i)\\.(jpg\|jpeg\|png\|xbm\|svg\|gif\|tiff\|psd\|bmp\|eps\|ps)\$") \~ TRUE, TRUE \~ FALSE ) ) p2_df \<- epa_http %\>% group_by(metodoHttp,is_image) %\>% summarise(peticiones = n())

write_xlsx(epa_http, "epa_http_data.xlsx")

####################### PREGUNTA 3 - FIN\

# VISUALIZACIÓN DE LOS RESULTADOS

## Generar al menos 2 gráficos distintos que permitan visualizar alguna característica relevante de los datos analizados. Estos deberán representar por lo menos 1 o 2 variables diferentes del data frame. Describid el gráfico e indicar cualquier observación destacable que se pueda apreciar gracias a la representación gráfica.

####################### PREGUNTA 4 - INICIO\

####################### PREGUNTA 4 - FIN\

# VISUALIZACIÓN DE LOS RESULTADOS

## Generar un gráfico que permita visualizar el número de peticiones servidas a lo largo del tiempo.

####################### PREGUNTA 5 - INICIO\

####################### PREGUNTA 5 - FIN\

# VISUALIZACIÓN DE LOS RESULTADOS

## Utilizando un algoritmo de aprendizaje no supervisado, realizad un análisis de clústering con k-means para los datos del servidor.

####################### PREGUNTA 6 - INICIO\

####################### PREGUNTA 6 - FIN\

# VISUALIZACIÓN DE LOS RESULTADOS

## Representar visualmente en gráficos de tipo scatter plot el resultado de vuestros clústering y interpretad el resultado obtenido.

####################### PREGUNTA 7 - INICIO  

####################### PREGUNTA 7 - FIN  

# \< FIN DE LA PRÁCTICA \>
